WebUI/Models/ErrorViewModel.cs
namespace Todo.WebUI.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebUI/Models/TodoItem/EditViewModel.cs
using System.ComponentModel.DataAnnotations;
using Todo.Domain.Enums;

namespace Todo.WebUI.Models.TodoItem;

public class EditViewModel
{
    public int Id { get; set; }
    
    [Required]
    public string Name { get; set; }
    public PriorityLevel Priority { get; set; }
    public Status Status { get; set; }
}

WebUI/Models/TodoItem/TodoItemCreateViewModel.cs
using System.ComponentModel.DataAnnotations;
using Todo.Domain.Enums;
using Todo.WebUI.Helpers;

namespace Todo.WebUI.Models.TodoItem;

public class TodoItemCreateViewModel
{
    [Required]
    [IsUnique]
    public string Name { get; set; }
    
    public PriorityLevel Priority { get; set; }
}

WebUI/Models/TodoItem/TodoViewModel.cs
using Todo.Application.TaskItems;

namespace Todo.WebUI.Models.TodoItem;

public class TodoViewModel
{
    public IEnumerable<TodoItemDto>? Todos { get; set; }
}

WebUI/Controllers/TodoItemsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Todo.Domain.Entities;
using Todo.WebUI.Models;
using Todo.WebUI.Models.TodoItem;
using Todo.WebUI.Services;

namespace Todo.WebUI.Controllers;

public class TodoItemsController : Controller
{
    private readonly ITodoItemService _todoItemService;

    public TodoItemsController(ITodoItemService todoItemService)
    {
        _todoItemService = todoItemService;
    }

    public async Task<IActionResult> Index()
    {
        var items = await _todoItemService.GetAll();
        var viewModel = new TodoViewModel()
        {
            Todos = items
        };
        return View(viewModel);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
    
    public async Task<IActionResult> Edit(int id)
    {
        var item = await _todoItemService.GetItemAsync(id);
        var editViewModel = new EditViewModel()
        {
            Id = item.Id,
            Name = item.Name,
            Status = item.Status,
            Priority = item.Priority
        };
        return View(editViewModel);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, EditViewModel todo)
    {
        if (!ModelState.IsValid)
            return RedirectToAction("Index");
        
        var successful = await _todoItemService.UpdateTodoAsync(
            new TodoItem()
            {
                Id = todo.Id,
                Name = todo.Name,
                Status = todo.Status,
                Priority = todo.Priority
            });

        if (!successful.Status)
            return BadRequest("Could not update todo.");
        
        return RedirectToAction("Index");
    }
    
    public async Task<IActionResult> Delete(int id)
    {
        var response = await _todoItemService.DeleteItemAsync(id);
        return response.Status ? RedirectToAction("Index") : BadRequest(response.Message);
    }

    public ViewResult Create() => View();
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name, Priority")]TodoItemCreateViewModel todo)
    {
        if (!ModelState.IsValid)
            return RedirectToAction("Index");
        
        var todoItem = new TodoItem
        {
            Name = todo.Name,
            Priority = todo.Priority
        };
        var successful = await _todoItemService.AddItemAsync(todoItem);
    
        if (!successful.Status)
            return BadRequest(new { error = "Could not add item." });
        
        return RedirectToAction("Index");
    }
}

WebUI/Views/Shared/_EditorScriptsPartial.cshtml
<script src="~/lib/simplemde/simplemde.min.js"></script>
<script>
    var simplemde = new SimpleMDE();
</script>
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

WebUI/Views/Shared/_EditorStylePartial.cshtml
<link rel="stylesheet" href="~/lib/simplemde/simplemde.min.css" />

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebUI.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="TodoItems" asp-action="Index">WebUI</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TodoItems" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TodoItems" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WebUI - <a asp-area="" asp-controller="TodoItems" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebUI/Views/TodoItems/Create.cshtml
@model Todo.WebUI.Models.TodoItem.TodoItemCreateViewModel
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Todo.Domain.Enums

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Todo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label">Priority</label>
                <select asp-for="Priority" class="form-control" 
                        asp-items="@Html.GetEnumSelectList<PriorityLevel>()"></select>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<partial name="_EditorStylePartial" />

@section Scripts {
    <partial name="_EditorScriptsPartial" />
}

WebUI/Views/TodoItems/Edit.cshtml
@model Todo.WebUI.Models.TodoItem.EditViewModel
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Todo.Domain.Enums

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit @Model.Id</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label">Priority</label>
                <select asp-for="Priority" class="form-control" 
                        asp-items="@Html.GetEnumSelectList<PriorityLevel>()"></select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label">Status</label>
                <select asp-for="Status" class="form-control" 
                        asp-items="@Html.GetEnumSelectList<Status>()"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">"Back to List"]</a>
</div>

WebUI/Views/TodoItems/Index.cshtml
@model Todo.WebUI.Models.TodoItem.TodoViewModel
@using Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
}

<h2>Todos</h2>

<table class="table">
    <thead>
        <tr>
            <th> Name </th>
            <th> Priority </th>
            <th> Status </th>
            <th>  </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Todos)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Priority
                </td>
                <td>
                    @item.Status
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<p> <a class="btn btn-success" asp-action="Create">Add Todo</a> </p>

<hr/>